/*
Creator: Dragon Prince
Date: 25.12.2011
Time:03:37 AM
*/
var randy,tester,turn,row=6;face=[];flag=[];
$(document).ready(function(){$("#face_1").click(function(){player(1,1)});$("#face_2").click(function(){player(2,2)});$("#face_3").click(function(){player(2,3)});$("#face_4").click(function(){player(2,4)});$("#face_5").click(function(){player(3,5)});$("#face_6").click(function(){player(3,6)});$("#face_7").click(function(){player(3,7)});$("#face_8").click(function(){player(3,8)});$("#face_9").click(function(){player(3,9)});$("#face_10").click(function(){player(4,10)});$("#face_11").click(function(){player(4,
11)});$("#face_12").click(function(){player(4,12)});$("#face_13").click(function(){player(4,13)});$("#face_14").click(function(){player(4,14)});$("#face_15").click(function(){player(4,15)});$("#face_16").click(function(){player(4,16)});$("#comp").click(function(){computer()});$("#comp").fadeTo("slow",0.3);$("#comp").hover(function(){$(this).fadeTo("slow",1)},function(){$(this).fadeTo("slow",0.3)})});
function player(b,a){row=b;5<=turn&&0!=face[row]&&(turn=row);turn==row&&0!=face[row]&&(face[row]--,$("#face_"+a).flyOffPage({retainSpace:{height:0,width:0,margin:0},tween:{opacity:0}}),flag[a]=1);0==face[1]+face[2]+face[3]+face[4]&&$.liteDialog("Gameover pal :P")}
function del_group(){1==randy&&($("#face_1").flyOffPage({retainSpace:{height:0,width:0,margin:0},tween:{opacity:0}}),flag[1]=1);if(2==randy)for(i=2;4>=i;i++)for(;1!=flag[i]&&face[randy]<tester;)$("#face_"+i).flyOffPage({retainSpace:{height:0,width:0,margin:0},tween:{opacity:0}}),flag[i]=1,tester--;if(3==randy)for(i=5;9>=i;i++)for(;1!=flag[i]&&face[randy]<tester;)$("#face_"+i).flyOffPage({retainSpace:{height:0,width:0,margin:0},tween:{opacity:0}}),flag[i]=1,tester--;if(4==randy)for(i=10;16>=i;i++)for(;1!=
flag[i]&&face[randy]<tester;)$("#face_"+i).flyOffPage({retainSpace:{height:0,width:0,margin:0},tween:{opacity:0}}),flag[i]=1,tester--}
function del(){1==randy&&($("#face_1").flyOffPage({retainSpace:{height:0,width:0,margin:0},tween:{opacity:0}}),face[randy]--,flag[1]=1);if(2==randy){temp=0;for(i=2;4>=i;i++)for(;1!=flag[i]&&0==temp;)$("#face_"+i).flyOffPage({retainSpace:{height:0,width:0,margin:0},tween:{opacity:0}}),flag[i]=1,face[randy]--,temp=1}if(3==randy){temp=0;for(i=5;9>=i;i++)for(;1!=flag[i]&&0==temp;)$("#face_"+i).flyOffPage({retainSpace:{height:0,width:0,margin:0},tween:{opacity:0}}),flag[i]=1,face[randy]--,temp=1}if(4==
randy){temp=0;for(i=10;16>=i;i++)for(;1!=flag[i]&&0==temp;)$("#face_"+i).flyOffPage({retainSpace:{height:0,width:0,margin:0},tween:{opacity:0}}),flag[i]=1,face[randy]--,temp=1}}function secret(){return 0==(face[1]^face[2]^face[3]^face[4])^1==(face[1]|face[2]|face[3]|face[4])}
function computer(){if(0!=face[1]+face[2]+face[3]+face[4]){if(5!=turn)if(turn=5,randy=Math.floor(4*Math.random()+1),secret()){for(;0==face[randy];)randy=randy%4+1;del()}else{for(;!secret();){for(randy=randy%4+1;0==face[randy];)randy=randy%4+1;for(tester=face[randy];!secret()&&0!=face[randy];)face[randy]--;secret()||(face[randy]=tester)}del_group()}0==face[1]+face[2]+face[3]+face[4]&&$.liteDialog("Awesomeeeeeeeee")}}
function nim(){face[1]=1;face[2]=3;face[3]=5;face[4]=7;flag=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];turn=6}window.onload=nim;